#!/usr/bin/env python3
"""Generate data/explicit_words.txt, the list the NSFW filter flags.

Run from the repository root:

    python scripts/gen_explicit_words.py

**This is a flag list, not an exclusion list, and the difference is the
point.** ``data/explicit_exclusions.txt`` is applied by
``gen_vocabulary.py`` when the wordlist is built, so the words it names
are simply absent and no setting can bring them back. The list written
here is consulted at *suggestion* time instead, so the words stay in the
dictionary, stay typable and stay learnable, and a user setting decides
whether the prediction bar volunteers them.

That makes being wrong far cheaper than it is for an exclusion, which is
what allows a mechanical rule here at all. A word wrongly flagged is one
the bar does not offer while the filter is on; a word wrongly excluded is
one nobody can ever predict.

Matching follows the convention ``explicit_exclusions.txt`` already
documents: a stem matches exactly, plus a closed set of inflectional
suffixes. **Never substring matching.** That is the Scunthorpe rule, and
without it ``class``, ``assess``, ``cocktail``, ``peacock``,
``dictionary``, ``analysis`` and ``shiitake`` all get flagged, which is
how a filter like this ends up being turned off and left off.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

#: Inflections a stem is allowed to carry, from explicit_exclusions.txt.
SUFFIXES = ("", "s", "es", "ed", "ing", "er", "ers", "y", "ies", "ish", "ier", "iest", "ily")

#: Sources of shipped vocabulary. Anything not in one of these cannot be
#: suggested, so flagging it would be noise in a file meant to be audited.
SOURCES = ("english-expanded.txt", "base_dictionary.txt")

#: Slur stems. These are the gap the exclusion list left: it was built to
#: cover swearing, so the generated wordlist has no common profanity in it
#: at all, while ethnic, sexual and disability slurs came through intact.
#: Kept in a separate block from the profanity stems below because the two
#: were found by different routes and a future reviewer should be able to
#: tell which is which.
SLUR_STEMS = (
    "chink",
    "coon",
    "dago",
    "darkie",
    "darky",
    "dyke",
    "fag",
    "faggot",
    "gook",
    "gyp",
    "halfbreed",
    "heeb",
    "honky",
    "injun",
    "jap",
    "kike",
    "kraut",
    "mick",
    "negress",
    "negro",
    "nigger",
    "nigga",
    "paki",
    "pickaninny",
    "raghead",
    "redskin",
    "retard",
    "sambo",
    "spic",
    # "spook" is deliberately absent. Its slur sense is real but rare, and
    # the stem also produces "spooky" and "spooked", which are ordinary
    # words. A filter that visibly swallows common words is one the user
    # turns off and leaves off, so the false positive costs more than the
    # miss.
    "squaw",
    "tranny",
    "wetback",
    "wog",
    "wop",
    "yid",
    "zipperhead",
)


def load_stems() -> list[str]:
    """The profanity stems already curated, plus the slur stems above."""
    path = DATA / "explicit_exclusions.txt"
    profanity = [
        line.strip().lower()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    return sorted(set(profanity) | set(SLUR_STEMS))


def shipped_words() -> set[str]:
    words: set[str] = set()
    for name in SOURCES:
        path = DATA / name
        if not path.exists():
            print(f"missing source: {path}", file=sys.stderr)
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            word = line.strip().lower()
            if word and not word.startswith("#"):
                words.add(word)
    return words


def main() -> int:
    stems = load_stems()
    words = shipped_words()

    forms = {stem + suffix for stem in stems for suffix in SUFFIXES}
    flagged = sorted(words & forms)

    out = DATA / "explicit_words.txt"
    header = (
        "# GENERATED by scripts/gen_explicit_words.py. Do not hand-edit.\n"
        "#\n"
        "# Words the NSFW filter suppresses from suggestions while it is on.\n"
        "# They remain in the dictionary, remain typable, and remain learnable:\n"
        "# this list governs what the bar volunteers, not what exists.\n"
        "#\n"
        "# Derived by matching curated stems against the shipped wordlists with a\n"
        "# closed suffix set, never by substring. See the generator for why.\n"
        f"# stems: {len(stems)}  shipped words scanned: {len(words)}  flagged: {len(flagged)}\n"
    )
    out.write_text(header + "\n".join(flagged) + "\n", encoding="utf-8")

    print(f"stems              : {len(stems)}")
    print(f"shipped words      : {len(words)}")
    print(f"flagged            : {len(flagged)}")
    print(f"written            : {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
