"""Generate a conservative Alpha-OSK vocabulary from an ESDB wordlist.

The input is the plain en_US.txt member from the pinned ESDB release archive.
Output is deterministic and contains only lower-case ASCII words, excluding
possessives, short fragments, and words already shipped by Alpha-OSK.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import zipfile
from pathlib import Path

WORD_RE = re.compile(r"[a-z]+(?:'[a-z]+)?\Z")
SOURCE_SHA256 = "caeb6ee8a38e98ccbd6e5c717889a1bab68073dcba8a9c0ca6570641926913e9"
SOURCE_URL = (
    "https://sourceforge.net/projects/wordlist/files/speller/2026.02.25/"
    "wordlist-en_US-2026.02.25.zip/download"
)
EXPLICIT_SUFFIXES = (
    "",
    "s",
    "es",
    "ed",
    "ing",
    "er",
    "ers",
    "y",
    "ies",
    "ish",
    "ier",
    "iest",
    "ily",
)


def excluded_forms(roots: set[str]) -> set[str]:
    return {root + suffix for root in roots for suffix in EXPLICIT_SUFFIXES}


def is_explicit_word(word: str, roots: set[str]) -> bool:
    """Apply exact-root filtering without removing safe compounds."""
    return word in excluded_forms(roots)


def words_from_file(path: Path) -> set[str]:
    words: set[str] = set()
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = line.strip().lower().split()
        if parts and not parts[0].startswith("#"):
            words.add(parts[0])
    return words


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("archive", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--base", type=Path, action="append", required=True)
    args = parser.parse_args()

    digest = hashlib.sha256(args.archive.read_bytes()).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(f"source SHA-256 mismatch: expected {SOURCE_SHA256}, got {digest}")

    existing = set().union(*(words_from_file(path) for path in args.base))
    exclusions_path = Path(__file__).parent.parent / "data" / "explicit_exclusions.txt"
    exclusions = {
        line.strip().lower()
        for line in exclusions_path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    excluded = excluded_forms(exclusions)
    with zipfile.ZipFile(args.archive) as archive:
        raw = archive.read("en_US.txt").decode("utf-8")

    selected: set[str] = set()
    for raw_word in raw.splitlines():
        word = raw_word.strip()
        if word != word.lower() or not WORD_RE.fullmatch(word):
            continue
        if len(word) <= 2 or word.endswith("'s") or word in existing:
            continue
        if word in excluded:
            continue
        if not any(char in "aeiouy" for char in word):
            continue
        if not any(char.isalpha() and char not in "aeiou" for char in word):
            continue
        selected.add(word)

    args.out.write_text(
        "# GENERATED by scripts/gen_vocabulary.py. Do not hand-edit.\n"
        "# Source: ESDB en_US dictionary, release 2026.02.25 (7e99eda).\n"
        f"# Source URL: {SOURCE_URL}\n"
        f"# Archive SHA-256: {SOURCE_SHA256}.\n"
        "# License and original notices: data/licenses/ESDB.txt.\n"
        "# Explicit exclusions: data/explicit_exclusions.txt, exact roots plus\n"
        "# documented inflections only; no substring matching.\n"
        "# Filter: lowercase ASCII words, no possessives, length > 2,\n"
        "# vowel and consonant required, excluding existing Alpha-OSK words.\n"
        "# Selection: every remaining size-60 word; no sampling or length cutoff.\n"
        "# ESDB export has no frequency rank. Runtime uses one base count per word.\n"
        + "\n".join(sorted(selected))
        + "\n",
        encoding="utf-8",
    )
    args.out.with_suffix(".manifest").write_text(
        f"source_url={SOURCE_URL}\n"
        "source_release=2026.02.25\nsource_commit=7e99eda\n"
        f"source_sha256={SOURCE_SHA256}\n"
        "source_member=en_US.txt\nsource_dictionary=ESDB size 60, American English\n"
        f"output_words={len(selected)}\n"
        "selection=all words remaining after filtering, sorted alphabetically\n"
        "filter=lowercase ASCII words, internal apostrophes, length greater than 2, "
        "vowel and consonant, no possessives, existing words excluded, "
        "explicit stems and inflections excluded by data/explicit_exclusions.txt\n",
        encoding="utf-8",
    )
    print(f"generated {len(selected)} words")


if __name__ == "__main__":
    main()
