#!/usr/bin/env python3
"""Generate data/explicit_words.txt, the list the NSFW filter flags.

Run from the repository root:

    python scripts/gen_explicit_words.py

**This is a flag list, not an exclusion list, and the difference is the
point.** ``data/slurs.txt`` is the exclusion list: ``gen_vocabulary.py``
leaves its words out of the wordlist, so no setting can bring them back.
The list written here is consulted at *suggestion* time instead, so the
words stay in the dictionary, stay typable and stay learnable, and a user
setting decides whether the prediction bar volunteers them.

That makes being wrong far cheaper than it is for an exclusion, which is
what allows a mechanical rule here at all. A word wrongly flagged is one
the bar does not offer while the filter is on; a word wrongly excluded is
one nobody can ever predict.

Matching follows the convention ``explicit_stems.txt`` already
documents: a stem matches exactly, plus a closed set of inflectional
suffixes. **Never substring matching.** That is the Scunthorpe rule, and
without it ``class``, ``assess``, ``cocktail``, ``peacock``,
``dictionary``, ``analysis`` and ``shiitake`` all get flagged, which is
how a filter like this ends up being turned off and left off.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

#: Inflections a stem is allowed to carry, from explicit_stems.txt.
SUFFIXES = ("", "s", "es", "ed", "ing", "er", "ers", "y", "ies", "ish", "ier", "iest", "ily")

#: Sources of shipped vocabulary. Anything not in one of these cannot be
#: suggested, so flagging it would be noise in a file meant to be audited.
#: The supplement was missing from this list at first, which left
#: "bullshit" and "negro" unflagged although the bar could offer both.
SOURCES = ("english-expanded.txt", "base_dictionary.txt", "google-20000-supplement.txt")

#: Words with a slur sense AND a common ordinary one, so they stay in the
#: vocabulary and are only kept off the bar while the filter is on. Exact
#: words, never stems: the stem list this replaced ("spic", "jap", "chink",
#: "retard") also caught "spiced", "japes", "chinking" and "retarder".
#:
#: Words whose main modern use is a slur are not here. They are removed from
#: the shipped wordlists outright (data/slurs.txt), so no setting offers
#: them and there is nothing left in the vocabulary for this file to flag.
FILTER_ONLY_WORDS = (
    "chink",  # a narrow gap: "a chink in the armour", "chinks of light"
    "chinks",
    "dyke",  # a variant spelling of "dike"
    "dykes",
    "fag",  # British for a cigarette
    "fags",
    "micks",  # plural of the name Mick
    "negro",  # historical proper names: the Negro Leagues
    "negroes",
)


def load_stems() -> list[str]:
    """The curated profanity stems."""
    path = DATA / "explicit_stems.txt"
    profanity = [
        line.strip().lower()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    return sorted(set(profanity))


def shipped_words() -> set[str]:
    words: set[str] = set()
    for name in SOURCES:
        path = DATA / name
        if not path.exists():
            print(f"missing source: {path}", file=sys.stderr)
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            word = line.strip().lower()
            if word and not word.startswith("#"):
                words.add(word)
    return words


def main() -> int:
    stems = load_stems()
    words = shipped_words()

    forms = {stem + suffix for stem in stems for suffix in SUFFIXES}
    flagged = sorted(words & (forms | set(FILTER_ONLY_WORDS)))

    out = DATA / "explicit_words.txt"
    header = (
        "# GENERATED by scripts/gen_explicit_words.py. Do not hand-edit.\n"
        "#\n"
        "# Words the NSFW filter suppresses from suggestions while it is on.\n"
        "# They remain in the dictionary, remain typable, and remain learnable:\n"
        "# this list governs what the bar volunteers, not what exists.\n"
        "#\n"
        "# Derived by matching curated stems against the shipped wordlists with a\n"
        "# closed suffix set, never by substring. See the generator for why.\n"
        f"# stems: {len(stems)}  shipped words scanned: {len(words)}  flagged: {len(flagged)}\n"
    )
    # LF on every platform: write_text translates "\n" to CRLF on Windows,
    # and the repo stores LF.
    out.write_text(header + "\n".join(flagged) + "\n", encoding="utf-8", newline="\n")

    print(f"stems              : {len(stems)}")
    print(f"shipped words      : {len(words)}")
    print(f"flagged            : {len(flagged)}")
    print(f"written            : {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
